FROM python:3.11-slim
WORKDIR /app

COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt

COPY gradio_app.py .
COPY linear_regression.pkl .
COPY random_forest.pkl .
COPY neural_network.pkl .
COPY scaler.pkl .

EXPOSE 7860
CMD ["python", "gradio_app.py"]
